### ISSUE TITLE
Create reader for HCL AppScan CodeSweep

### ISSUE THREAD

**Issue by darkspirit510** [OWASP-Benchmark/BenchmarkUtils#19]
OWASPs overview page for free/open source scanners contains "HCL AppScan CodeSweep", but there is no reader for it, yet. This issue is a reminder to write a matching reader.

See: https://owasp.org/www-community/Free_for_Open_Source_Application_Security_Tools

**Comment by davewichers** [comment]
@darkspirit510 - do you want to look into this tool? This ticket has been sitting out here for 2 years. I'm wondering if the file format is similar to the other HCL tools we support so this would be quick/easy.

**Comment by darkspirit510** [comment]
@davewichers back then there was only a plugin for Visual Code and I was not able to generate a report. I just checked and there is a GitHub action using CodeSweep cloud, but it requires registration and I don't want to register just to create a report ☺️ 

@mattmurp is the main developer of the GitHub action. Maybe he can provide a result file to us so we could create a reader? He already contributed to the Benchmark project

**Comment by mattmurp** [comment]
@darkspirit510 @davewichers CodeSweep is designed to only scan modified/added code, not an entire project. So it doesn't fit the model of producing a single result file that can be compared against the benchmark.

**Comment by darkspirit510** [comment]
@mattmurp thank you for your reply! In that case, this issue has to be closed.
