### ISSUE TITLE
Improve parser for wapiti json

### ISSUE THREAD

**Issue by Qwarctick** [OWASP-Benchmark/BenchmarkUtils#72]
Hello,
I'm working with Wapiti and I'm having some trouble generating scorecards in json format correctly. 

I saw that you had a parser for Wapiti's json format, but it doesn't seem to have been updated since a long time (https://github.com/OWASP-Benchmark/BenchmarkUtils/blob/main/plugin/src/main/java/org/owasp/benchmarkutils/score/parsers/WapitiJsonReader.java). The json example in the tests returns 0% for all categories, so I'm pretty confident that the parser doesn't work very well.

I can work on it but I can't find any information about the corresponding tags. For example, `CRLF Injection` is for label `93` but what does that mean? 

Thanks in advance :)

**Comment by davewichers** [comment]
@darkspirit510 - can you help @Qwarctick with this?  @Qwarctick - can you email a copy of your Wapiti JSON results file (along with the script/instructions on how you generated it), to: dave.wichers@owasp.org and I'll forward to @darkspirit510 and he'll likely just fix it for you. He's generally super quick on stuff like this.

**Comment by darkspirit510** [comment]
Hi @Qwarctick,

thank you for reaching out. Maybe you misunderstood the test files. Did you use the one from the results dir for the tests at `https://github.com/OWASP-Benchmark/BenchmarkUtils/tree/main/plugin/src/test/resources/testfiles`? Those intentionally do not contain ANY real finding to honor commercial tools disclousure policies. So to just prevent any issues here, the test files are just fake and contain one or two dummy results to test against. If you want to know how well a tool scores, you'll have to create a result file on your own.

Yes, the BenchmarkJava project contains some (older) actual result files, but those are all from open source tools and to test the whole BenchmarkJava and BenchmarkUtils project.

**Comment by Qwarctick** [comment]
Ok, thanks for the information. I can see why it's done that way.

I'm generating a json file. I'll send it to you at address [dave.wichers@owasp.org](mailto:dave.wichers@owasp.org) as soon as it's ready.

**Comment by darkspirit510** [comment]
@Qwarctick My PR got merged, please recheck your result file and see if this issue can be closed 😊

**Comment by Qwarctick** [comment]
Maybe I failed somewhere, but I tested with the json file I sended you by email. 

Without the PR: 
![Benchmark_v1 2_Scorecard_for_Wapiti_v608717d4a9f64e88bdc6faa796d37856](https://github.com/OWASP-Benchmark/BenchmarkUtils/assets/31954718/a08555ff-fad0-42e0-a490-49265cadc84b)

With the PR: 
![Benchmark_v1 2_Scorecard_for_Wapiti_vmerged](https://github.com/OWASP-Benchmark/BenchmarkUtils/assets/31954718/f9a2fcbc-950b-47b3-9507-6af872425c10)

I built the sources with `mvn install`, then used the script [createScorecards.sh](https://github.com/OWASP-Benchmark/BenchmarkUtils/blob/main/examplescripts_configfiles/createScorecards.sh)

**Comment by darkspirit510** [comment]
Are you sure that you pulled `BenchmarkUtils` correctly? I just did a clean checkout, `mvn install` and generated the scorecard. I get results, as expected even better than yours.

![Benchmark_v1 2_Scorecard_for_Wapiti_vmerged](https://github.com/OWASP-Benchmark/BenchmarkUtils/assets/17259447/4be7c2c9-83ba-4a80-863f-e7260e22cbd2)

**Comment by Qwarctick** [comment]
My bad, I used a wrong expectedresults file. It works well. Well done !
